function results = myimfcn(ref_im1)
%Image Processing Function
%
% IM      - Input image.
% RESULTS - A scalar structure with the processing results.
%

%--------------------------------------------------------------------------
% Auto-generated by imageBatchProcessor App. 
%
% When used by the App, this function will be called for every input image
% file automatically. IM contains the input image as a matrix. RESULTS is a
% scalar structure containing the results of this processing function.
%
%--------------------------------------------------------------------------


%% logplottransformation
ref_doub=im2double(ref_im1);
ref_im=ref_doub;
[r,c]=size(ref_im);
factor=3.5;
for i=1:r
    for j=1:c
        ref_im(i,j)= factor*log(1+ ref_doub(i,j));
    end
end


%% histogram equilization stretched
ref_im=imadjust(ref_im,[0.2,0.6],[0.0,1.0]);
ref_im=histeq(ref_im);


%% call segmentation function
ref_seg=segmentImage(ref_im);
E = edge(ref_seg,'canny');


%% Place Result
results.c_edge=E;
